### PR TITLE
New `apply_if_some...` functions, Doc updates

### PR DESCRIPTION
**Pull request by geo-ant**
Hi Ben, 

I am a happy user of this crate, but I ran into a problem at work when using the crate and wondered if you were open to including my additions. The main changes are:

* relaxed requirements for the closures in `apply_if_...` functions. They used to be bounded on `Fn`, which is stricter than they need to be. I now bounded them on `FnOnce`.
* I added two new functions `apply_if_some` and the mutable counterpart `apply_if_some_mut`, which allow us to conditionally invoke builder functions based on the contents of an optional. Note that this allows us to work with `Option` but also `Result` values (via `.ok()`) and `.err()`, which is why I felt we wouldn't need `apply_if_ok` and `apply_if_err` variants.
* I updated the documentation. The readme now has examples and is also included into the `lib.rs`. This has the advantage that there's only one place for the docs and that the readme is checked during the doc tests. It will not go out of sync with the crate.

Please let me know if you're open to merging those changes in. They would be super useful to me.

### CODE REVIEW

**Review by bavalpey — APPROVED** [review]
This is great

**Comment by bavalpey** [comment]
I'm glad you have found the crate useful! 

This is incredibly well reasoned, too.

Honestly, when I originally wrote this crate, I was fuzzy on the difference between `Fn` and `FnOnce`. (Back then I thought the supertrait relationship was the other way).

Really this is very welcome.

I also like the apply_if_some.  That's a pattern I've actually been using a bit, though generally I've done so by having the apply if closure just call ``option.is_some()``

**Review by bavalpey — APPROVED** [review]

**Comment by geo-ant** [comment]
Thank you for merging those changes in and for doing it so quickly! I saw you already pushed the new version on crates.io, which means I can use it today. That makes me very happy :)

**Comment by bavalpey** [comment]
Yeah, happy to help!

**Pull request merged**
